// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginReply struct {
	Uid       string `json:"uid"`
	NickName  string `json:"nickName"`
	UserToken string `json:"userToken"`
}

type UserInfoResponse struct {
	Uid      string `json:"uid"`
	NickName string `json:"nickName"`
	Sex      int64  `json:"sex"`
}

type UserDnsResponse struct {
	Dns []string `json:"dns"`
}
